import { useId, useMemo, useState } from 'react'
import { Field, Icon, titleCase } from './ui.jsx'

/**
 * Resolve what someone typed against the app's colour vocabulary.
 *
 * The table comes from the backend (`meta.colour_lookup`), generated by the
 * same code that normalises on save, so the swatch shown while typing is the
 * colour that will actually be stored. Anything unrecognised is reported as
 * unrecognised rather than quietly corrected — it is still saved as typed.
 */
export function resolveColour(value, meta) {
  const raw = String(value ?? '').trim()
  if (!raw) return { empty: true, known: false, name: '', hex: null }

  const blanks = meta?.colour_blanks || []
  if (blanks.includes(raw.toLowerCase())) {
    return { empty: true, known: false, name: '', hex: null }
  }

  const lookup = meta?.colour_lookup || {}
  const swatches = meta?.colours || []
  const key = raw.toLowerCase().replace(/[^a-z0-9 ]+/g, ' ').replace(/\s+/g, ' ').trim()
  const name = lookup[key]
  if (name) {
    const entry = swatches.find((c) => c.name === name)
    return {
      empty: false, known: true, name,
      hex: entry?.hex || null,
      renamed: name !== raw.toLowerCase(),
    }
  }
  if (/^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(raw)) {
    return { empty: false, known: true, name: raw, hex: raw, renamed: false }
  }
  return { empty: false, known: false, name: raw, hex: null }
}

/** A small round swatch, or a dashed ring when there is no colour to show. */
export function Swatch({ hex, size = 14, title }) {
  return (
    <span
      title={title}
      className="inline-block shrink-0 rounded-full ring-1"
      style={{
        width: size,
        height: size,
        background: hex || 'transparent',
        borderStyle: hex ? undefined : 'dashed',
        '--tw-ring-color': hex ? 'var(--border)' : 'var(--muted)',
      }}
    />
  )
}

function Suggestion({ hex, name, active, note, onClick }) {
  return (
    <button
      type="button" onClick={onClick} className="chip" title={note}
      style={active ? { borderColor: 'var(--accent)', color: 'var(--accent)' } : undefined}
    >
      <Swatch hex={hex} size={12} />
      {titleCase(name)}
    </button>
  )
}

/**
 * One colour field: a text box, the colours read from the photo, and the full
 * vocabulary behind a toggle.
 *
 * The photo suggestions carry their runners-up. Some readings genuinely cannot
 * be decided from pixels — white fabric and a pale grey marl land two Lab units
 * apart — so rather than guessing harder, the other reading sits next to the
 * first and is one tap away.
 */
export default function ColourField({
  label, hint, value, onChange, meta, palette = [], options = [],
}) {
  const [browsing, setBrowsing] = useState(false)
  const listId = useId()
  const reading = resolveColour(value, meta)
  const swatches = meta?.colours || []
  const current = (reading.name || '').toLowerCase()

  const { picks, alternates } = useMemo(() => {
    const seen = new Set()
    const picks = []
    for (const entry of palette) {
      const name = (entry?.name || '').toLowerCase()
      if (!name || seen.has(name)) continue
      seen.add(name)
      picks.push({
        name,
        hex: entry.hex,
        note: entry.share != null
          ? `${titleCase(name)} — ${Math.round(entry.share * 100)}% of the photo`
          : titleCase(name),
      })
    }
    const alternates = []
    for (const entry of palette) {
      for (const name of entry?.alternatives || []) {
        const key = String(name).toLowerCase()
        if (!key || seen.has(key)) continue
        seen.add(key)
        alternates.push({
          name: key,
          hex: swatches.find((c) => c.name === key)?.hex || null,
          note: `Could also be ${key}`,
        })
      }
    }
    return { picks, alternates }
  }, [palette, swatches])

  const pick = (name) => onChange(current === name ? '' : titleCase(name))

  return (
    <Field label={label} hint={hint}>
      <div className="relative">
        <span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2">
          <Swatch hex={reading.hex} size={15} />
        </span>
        <input
          className="input pl-9 pr-9"
          value={value || ''}
          list={options.length ? listId : undefined}
          autoCapitalize="words"
          autoComplete="off"
          placeholder="Navy"
          onChange={(e) => onChange(e.target.value)}
        />
        {value && (
          <button
            type="button" onClick={() => onChange('')}
            className="absolute right-2 top-1/2 -translate-y-1/2 rounded-full p-1"
            style={{ color: 'var(--muted)' }} aria-label={`Clear ${label}`}
          >
            <Icon name="close" size={14} />
          </button>
        )}
      </div>

      {!reading.empty && !reading.known && (
        <p className="mt-1 text-xs" style={{ color: 'var(--warn)' }}>
          Not a colour the app knows, so it will not group this into a laundry pile
          or match it in an outfit. It is still saved as typed.
        </p>
      )}
      {reading.known && reading.renamed && (
        <p className="mt-1 text-xs" style={{ color: 'var(--muted)' }}>
          Saved as <strong>{titleCase(reading.name)}</strong>.
        </p>
      )}

      {(picks.length > 0 || alternates.length > 0) && (
        <div className="mt-1.5 space-y-1">
          {picks.length > 0 && (
            <div className="rail">
              {picks.map((c) => (
                <Suggestion key={c.name} {...c} active={current === c.name}
                            onClick={() => pick(c.name)} />
              ))}
            </div>
          )}
          {alternates.length > 0 && (
            <div className="rail items-center">
              <span className="shrink-0 text-[0.68rem]" style={{ color: 'var(--muted)' }}>
                or
              </span>
              {alternates.map((c) => (
                <Suggestion key={c.name} {...c} active={current === c.name}
                            onClick={() => pick(c.name)} />
              ))}
            </div>
          )}
        </div>
      )}

      <button
        type="button"
        className="btn btn-ghost mt-1 !px-1 !py-0.5 text-xs"
        onClick={() => setBrowsing((v) => !v)}
        aria-expanded={browsing}
      >
        <Icon name="chevron" size={13}
              style={{ transform: browsing ? 'rotate(180deg)' : 'none' }} />
        {browsing ? 'Hide all colours' : 'All colours'}
      </button>

      {browsing && (
        <div className="card mt-1 max-h-56 overflow-y-auto p-2">
          <div className="grid grid-cols-2 gap-1 sm:grid-cols-3">
            {swatches.map((c) => (
              <button
                key={c.name} type="button" onClick={() => pick(c.name)}
                className="flex items-center gap-2 rounded-lg px-2 py-1.5 text-left text-sm"
                style={current === c.name
                  ? { background: 'var(--accent-soft)', color: 'var(--accent)' }
                  : undefined}
              >
                <Swatch hex={c.hex} size={14} />
                <span className="truncate">{titleCase(c.name)}</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {options.length > 0 && (
        <datalist id={listId}>
          {options.map((o) => <option key={o} value={o} />)}
        </datalist>
      )}
    </Field>
  )
}
